version: '3.8'
services:
  backend:
    container_name: backend
    build: .
    tty: true
    restart: always
    ports:
      - '9002:9002'
    volumes:
      - type: bind
        source: .
        target: /backend
    env_file: .env
  kintai_postgres:
    image: postgres:14
    container_name: kintai_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=multi
    volumes:
      - kintai_postgres:/var/lib/postgresql/kintai_data
    ports:
      - 5435:5432
volumes:
  kintai_postgres:
