version: '3.8'
services:
  backend:
    container_name: backend
    build: .
    tty: true
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - type: bind
        source: .
        target: /backend
