version: '3.8'
services:
  backend:
    container_name: backend
    build: .
    tty: true
    restart: always
    ports:
      - '9002:9002'
    volumes:
      - type: bind
        source: .
        target: /backend
    env_file: .env
  kintai_postgres:
    image: postgres:14
    container_name: kintai_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB= ${DB_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
volumes:
  postgres:
